### PR TITLE
Todo

### PR DESCRIPTION
**Pull request by brytebee**
## Add functionality 🧑‍💼 
In this PR, I have accomplished the following:
- added structure to the app
- styled the app
- added event handling ability to enable inputs
- added routes
- added react icons

### CODE REVIEW

**Review by Munsa1 — APPROVED** [review]
our project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by brytebee** [comment]
Hello, @Munsa1 👋👋,

Thanks for the warm-hearted review 👀👀.



I'll go ahead to merge and move on to the next milestone 🏁🏁.

**_Happy Hacking 😄😄_**

**Review by Anny85-code — APPROVED** [review]
Hi @brytebee 👋 ,

Great effort you put in to get this project completed, keep up the good work.
you have implemented all the requirements needed for a standard project;
- [x] Good commit messages,
- [x] Descriptive pull request.
However, there is what I feel it's an oversight on your part, I will suggest you fix it to spice up your project professionally;
- [x] I will suggest you update your readme file to match your current project. this will reference your project appropriately.
Other than that, there is nothing more to say than to merge. your project is completed.
Congratulations!!! 🥳 🎈  

catglass

**Review by Anny85-code — CHANGES_REQUESTED** [review]
Hi @brytebee 👋 ,

Great job so far on your project, you have put in great effort to get to this stage of the project, good job!!.
You have implemented;
- [x] Descriptive PR.
- [x] Descriptive and meaningful commit messages. 
However, there are a few suggestions I will like you to implement to spice your project professionally and so you move to the next level;
- [x] I would suggest you set eslint and stylint in your project. this will help checkmate best coding practices.
- [x] I would suggest you update your readme file to reference the current project and include a live demo of this project. this adds a good description to a project.
- [x] I would suggest you use proper Gitflow. you can refer to this [link](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=Gitflow%20Workflow%20is%20a%20Git%20workflow%20that%20helps,strict%20branching%20model%20designed%20around%20the%20project%20release.).
Feel free to drop a comment or any question in the comment section.
happy coding 😄 
almost-there
Please do not open another pull request on this issue. thanks

**Comment by brytebee** [comment]
Hello @Anny85-code 👋,

Thanks for the review, I will make the suggested changes.

**Review by Anny85-code — APPROVED** [review]
Hi @brytebee 👋 ,

Good job for implementing the changes.
with that, there is nothing else to say than to merge.
Congratulations. 🎈 
complete meme

**Pull request merged**
